# Generated by Django 4.1 on 2022-09-10 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Familiares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='familiarDirecto',
        ),
    ]
